// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: validation.proto

package phive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidationService_ListVesIds_FullMethodName  = "/invopop.phive.v1.ValidationService/ListVesIds"
	ValidationService_ValidateXml_FullMethodName = "/invopop.phive.v1.ValidationService/ValidateXml"
)

// ValidationServiceClient is the client API for ValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for phive validation operations
type ValidationServiceClient interface {
	// Lists all available VESIDs (Validation Execution Set IDs)
	ListVesIds(ctx context.Context, in *ListVesIdsRequest, opts ...grpc.CallOption) (*ListVesIdsResponse, error)
	// Validates an XML document against a specific VESID
	ValidateXml(ctx context.Context, in *ValidateXmlRequest, opts ...grpc.CallOption) (*ValidateXmlResponse, error)
}

type validationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationServiceClient(cc grpc.ClientConnInterface) ValidationServiceClient {
	return &validationServiceClient{cc}
}

func (c *validationServiceClient) ListVesIds(ctx context.Context, in *ListVesIdsRequest, opts ...grpc.CallOption) (*ListVesIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVesIdsResponse)
	err := c.cc.Invoke(ctx, ValidationService_ListVesIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationServiceClient) ValidateXml(ctx context.Context, in *ValidateXmlRequest, opts ...grpc.CallOption) (*ValidateXmlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateXmlResponse)
	err := c.cc.Invoke(ctx, ValidationService_ValidateXml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidationServiceServer is the server API for ValidationService service.
// All implementations must embed UnimplementedValidationServiceServer
// for forward compatibility.
//
// Service definition for phive validation operations
type ValidationServiceServer interface {
	// Lists all available VESIDs (Validation Execution Set IDs)
	ListVesIds(context.Context, *ListVesIdsRequest) (*ListVesIdsResponse, error)
	// Validates an XML document against a specific VESID
	ValidateXml(context.Context, *ValidateXmlRequest) (*ValidateXmlResponse, error)
	mustEmbedUnimplementedValidationServiceServer()
}

// UnimplementedValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidationServiceServer struct{}

func (UnimplementedValidationServiceServer) ListVesIds(context.Context, *ListVesIdsRequest) (*ListVesIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVesIds not implemented")
}
func (UnimplementedValidationServiceServer) ValidateXml(context.Context, *ValidateXmlRequest) (*ValidateXmlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateXml not implemented")
}
func (UnimplementedValidationServiceServer) mustEmbedUnimplementedValidationServiceServer() {}
func (UnimplementedValidationServiceServer) testEmbeddedByValue()                           {}

// UnsafeValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationServiceServer will
// result in compilation errors.
type UnsafeValidationServiceServer interface {
	mustEmbedUnimplementedValidationServiceServer()
}

func RegisterValidationServiceServer(s grpc.ServiceRegistrar, srv ValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidationService_ServiceDesc, srv)
}

func _ValidationService_ListVesIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVesIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServiceServer).ListVesIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationService_ListVesIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServiceServer).ListVesIds(ctx, req.(*ListVesIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationService_ValidateXml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateXmlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServiceServer).ValidateXml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationService_ValidateXml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServiceServer).ValidateXml(ctx, req.(*ValidateXmlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidationService_ServiceDesc is the grpc.ServiceDesc for ValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invopop.phive.v1.ValidationService",
	HandlerType: (*ValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVesIds",
			Handler:    _ValidationService_ListVesIds_Handler,
		},
		{
			MethodName: "ValidateXml",
			Handler:    _ValidationService_ValidateXml_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validation.proto",
}
