// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: validation.proto

package phive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to list all available VESIDs
type ListVesIdsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter to match VESIDs by pattern (e.g., "com.helger.*")
	Filter        string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVesIdsRequest) Reset() {
	*x = ListVesIdsRequest{}
	mi := &file_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVesIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVesIdsRequest) ProtoMessage() {}

func (x *ListVesIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVesIdsRequest.ProtoReflect.Descriptor instead.
func (*ListVesIdsRequest) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ListVesIdsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Response containing list of available VESIDs
type ListVesIdsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available VESID strings
	Vesids []*VesIdInfo `protobuf:"bytes,1,rep,name=vesids,proto3" json:"vesids,omitempty"`
	// Error message if the listing failed
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVesIdsResponse) Reset() {
	*x = ListVesIdsResponse{}
	mi := &file_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVesIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVesIdsResponse) ProtoMessage() {}

func (x *ListVesIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVesIdsResponse.ProtoReflect.Descriptor instead.
func (*ListVesIdsResponse) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ListVesIdsResponse) GetVesids() []*VesIdInfo {
	if x != nil {
		return x.Vesids
	}
	return nil
}

func (x *ListVesIdsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Information about a VESID
type VesIdInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The VESID in coordinate format (e.g., "com.helger.phive:test_xsd:1.0")
	Vesid string `protobuf:"bytes,1,opt,name=vesid,proto3" json:"vesid,omitempty"`
	// Human-readable name/description if available
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the validation set
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Status (e.g., "VALID", "DEPRECATED", etc.)
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VesIdInfo) Reset() {
	*x = VesIdInfo{}
	mi := &file_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VesIdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VesIdInfo) ProtoMessage() {}

func (x *VesIdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VesIdInfo.ProtoReflect.Descriptor instead.
func (*VesIdInfo) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{2}
}

func (x *VesIdInfo) GetVesid() string {
	if x != nil {
		return x.Vesid
	}
	return ""
}

func (x *VesIdInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VesIdInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VesIdInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request to validate an XML document
type ValidateXmlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The VESID to use for validation (e.g., "com.helger.phive:test_xsd:1.0")
	// Can use pseudo-versions like "latest" or "latest-release"
	Vesid string `protobuf:"bytes,1,opt,name=vesid,proto3" json:"vesid,omitempty"`
	// XML content as bytes
	XmlContent []byte `protobuf:"bytes,2,opt,name=xml_content,json=xmlContent,proto3" json:"xml_content,omitempty"`
	// Optional: source identifier for logging/tracking
	SourceIdentifier string `protobuf:"bytes,3,opt,name=source_identifier,json=sourceIdentifier,proto3" json:"source_identifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateXmlRequest) Reset() {
	*x = ValidateXmlRequest{}
	mi := &file_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateXmlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateXmlRequest) ProtoMessage() {}

func (x *ValidateXmlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateXmlRequest.ProtoReflect.Descriptor instead.
func (*ValidateXmlRequest) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateXmlRequest) GetVesid() string {
	if x != nil {
		return x.Vesid
	}
	return ""
}

func (x *ValidateXmlRequest) GetXmlContent() []byte {
	if x != nil {
		return x.XmlContent
	}
	return nil
}

func (x *ValidateXmlRequest) GetSourceIdentifier() string {
	if x != nil {
		return x.SourceIdentifier
	}
	return ""
}

// Response from XML validation
type ValidateXmlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall validation success
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// The resolved VESID that was used (if pseudo-version was used)
	ResolvedVesid string `protobuf:"bytes,2,opt,name=resolved_vesid,json=resolvedVesid,proto3" json:"resolved_vesid,omitempty"`
	// Validation results for each validation layer
	Results []*ValidationLayerResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	// Error message if validation failed to execute
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Timestamp when validation was performed (ISO 8601 format)
	Timestamp     string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateXmlResponse) Reset() {
	*x = ValidateXmlResponse{}
	mi := &file_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateXmlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateXmlResponse) ProtoMessage() {}

func (x *ValidateXmlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateXmlResponse.ProtoReflect.Descriptor instead.
func (*ValidateXmlResponse) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateXmlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateXmlResponse) GetResolvedVesid() string {
	if x != nil {
		return x.ResolvedVesid
	}
	return ""
}

func (x *ValidateXmlResponse) GetResults() []*ValidationLayerResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ValidateXmlResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidateXmlResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Result from a single validation layer (e.g., XSD, Schematron)
type ValidationLayerResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of validation (e.g., "XSD", "Schematron", "EDIFACT")
	ValidationType string `protobuf:"bytes,1,opt,name=validation_type,json=validationType,proto3" json:"validation_type,omitempty"`
	// Artifact ID used for this validation
	ArtifactId string `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Success indicator for this layer
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// List of errors found in this layer
	Errors []*ValidationError `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	// List of warnings (if any)
	Warnings      []*ValidationError `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationLayerResult) Reset() {
	*x = ValidationLayerResult{}
	mi := &file_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationLayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationLayerResult) ProtoMessage() {}

func (x *ValidationLayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationLayerResult.ProtoReflect.Descriptor instead.
func (*ValidationLayerResult) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationLayerResult) GetValidationType() string {
	if x != nil {
		return x.ValidationType
	}
	return ""
}

func (x *ValidationLayerResult) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ValidationLayerResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidationLayerResult) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationLayerResult) GetWarnings() []*ValidationError {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Validation error or warning
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error level (ERROR, WARN, INFO)
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// Error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Location in the document (line number if available)
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// XPath or other locator
	Xpath string `protobuf:"bytes,4,opt,name=xpath,proto3" json:"xpath,omitempty"`
	// Test ID (for Schematron rules)
	TestId string `protobuf:"bytes,5,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	// Additional error details
	Details       map[string]string `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_validation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{6}
}

func (x *ValidationError) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ValidationError) GetXpath() string {
	if x != nil {
		return x.Xpath
	}
	return ""
}

func (x *ValidationError) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ValidationError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_validation_proto protoreflect.FileDescriptor

const file_validation_proto_rawDesc = "" +
	"\n" +
	"\x10validation.proto\x12\x10invopop.phive.v1\"+\n" +
	"\x11ListVesIdsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"n\n" +
	"\x12ListVesIdsResponse\x123\n" +
	"\x06vesids\x18\x01 \x03(\v2\x1b.invopop.phive.v1.VesIdInfoR\x06vesids\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"g\n" +
	"\tVesIdInfo\x12\x14\n" +
	"\x05vesid\x18\x01 \x01(\tR\x05vesid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"x\n" +
	"\x12ValidateXmlRequest\x12\x14\n" +
	"\x05vesid\x18\x01 \x01(\tR\x05vesid\x12\x1f\n" +
	"\vxml_content\x18\x02 \x01(\fR\n" +
	"xmlContent\x12+\n" +
	"\x11source_identifier\x18\x03 \x01(\tR\x10sourceIdentifier\"\xdc\x01\n" +
	"\x13ValidateXmlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eresolved_vesid\x18\x02 \x01(\tR\rresolvedVesid\x12A\n" +
	"\aresults\x18\x03 \x03(\v2'.invopop.phive.v1.ValidationLayerResultR\aresults\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\xf5\x01\n" +
	"\x15ValidationLayerResult\x12'\n" +
	"\x0fvalidation_type\x18\x01 \x01(\tR\x0evalidationType\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x129\n" +
	"\x06errors\x18\x04 \x03(\v2!.invopop.phive.v1.ValidationErrorR\x06errors\x12=\n" +
	"\bwarnings\x18\x05 \x03(\v2!.invopop.phive.v1.ValidationErrorR\bwarnings\"\x92\x02\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x14\n" +
	"\x05xpath\x18\x04 \x01(\tR\x05xpath\x12\x17\n" +
	"\atest_id\x18\x05 \x01(\tR\x06testId\x12H\n" +
	"\adetails\x18\x06 \x03(\v2..invopop.phive.v1.ValidationError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc8\x01\n" +
	"\x11ValidationService\x12W\n" +
	"\n" +
	"ListVesIds\x12#.invopop.phive.v1.ListVesIdsRequest\x1a$.invopop.phive.v1.ListVesIdsResponse\x12Z\n" +
	"\vValidateXml\x12$.invopop.phive.v1.ValidateXmlRequest\x1a%.invopop.phive.v1.ValidateXmlResponseB6\n" +
	"\x03rpcB\x0fValidationProtoZ\x1egithub.com/invopop/phive;phiveb\x06proto3"

var (
	file_validation_proto_rawDescOnce sync.Once
	file_validation_proto_rawDescData []byte
)

func file_validation_proto_rawDescGZIP() []byte {
	file_validation_proto_rawDescOnce.Do(func() {
		file_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validation_proto_rawDesc), len(file_validation_proto_rawDesc)))
	})
	return file_validation_proto_rawDescData
}

var file_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_validation_proto_goTypes = []any{
	(*ListVesIdsRequest)(nil),     // 0: invopop.phive.v1.ListVesIdsRequest
	(*ListVesIdsResponse)(nil),    // 1: invopop.phive.v1.ListVesIdsResponse
	(*VesIdInfo)(nil),             // 2: invopop.phive.v1.VesIdInfo
	(*ValidateXmlRequest)(nil),    // 3: invopop.phive.v1.ValidateXmlRequest
	(*ValidateXmlResponse)(nil),   // 4: invopop.phive.v1.ValidateXmlResponse
	(*ValidationLayerResult)(nil), // 5: invopop.phive.v1.ValidationLayerResult
	(*ValidationError)(nil),       // 6: invopop.phive.v1.ValidationError
	nil,                           // 7: invopop.phive.v1.ValidationError.DetailsEntry
}
var file_validation_proto_depIdxs = []int32{
	2, // 0: invopop.phive.v1.ListVesIdsResponse.vesids:type_name -> invopop.phive.v1.VesIdInfo
	5, // 1: invopop.phive.v1.ValidateXmlResponse.results:type_name -> invopop.phive.v1.ValidationLayerResult
	6, // 2: invopop.phive.v1.ValidationLayerResult.errors:type_name -> invopop.phive.v1.ValidationError
	6, // 3: invopop.phive.v1.ValidationLayerResult.warnings:type_name -> invopop.phive.v1.ValidationError
	7, // 4: invopop.phive.v1.ValidationError.details:type_name -> invopop.phive.v1.ValidationError.DetailsEntry
	0, // 5: invopop.phive.v1.ValidationService.ListVesIds:input_type -> invopop.phive.v1.ListVesIdsRequest
	3, // 6: invopop.phive.v1.ValidationService.ValidateXml:input_type -> invopop.phive.v1.ValidateXmlRequest
	1, // 7: invopop.phive.v1.ValidationService.ListVesIds:output_type -> invopop.phive.v1.ListVesIdsResponse
	4, // 8: invopop.phive.v1.ValidationService.ValidateXml:output_type -> invopop.phive.v1.ValidateXmlResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_validation_proto_init() }
func file_validation_proto_init() {
	if File_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validation_proto_rawDesc), len(file_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_validation_proto_goTypes,
		DependencyIndexes: file_validation_proto_depIdxs,
		MessageInfos:      file_validation_proto_msgTypes,
	}.Build()
	File_validation_proto = out.File
	file_validation_proto_goTypes = nil
	file_validation_proto_depIdxs = nil
}
